### ISSUE TITLE
feature request: make glob support multiple * operators

### ISSUE THREAD

**Issue by WuTheFWasThat** [cshesse/blobfile#27]
am curious what it would take to get this to work, at least on gcs!  (seems probably annoying, although gsutil supports this)

**Comment by cshesse** [comment]
I ran into a few super slow listings with gfile which made me not want to have complex pattern support in blobfile.  Not sure if gsutil has the same issue.

I can think of two ways to do this:

1) Do the current setup (single query) but do additional filtering client side to reduce the list to only the matching blobs
2) Wildcards not match "/" so do a series of queries while setting the `delimiter` parameter to "/".  This would end up querying less total objects.  Setting `delimiter` does seem to be more performant than querying all objects, so if you manage to avoid listing enough objects, the extra query overhead could be paid for by the savings.

`gsutil help wildcards` describes the gsutil patterns (which uses option 2 for "*/*" and option 1 for "**"), and I'd be fine if `blobfile` supported that since it should be backward-compatible with the current setup, but I'm not planning to implement it currently.

**Comment by cshesse** [comment]
I added option #1, we'll see how bad the performance is in practice.  Someday it would be nice to have not-so-inefficient glob: https://github.com/cshesse/blobfile/issues/31

**Comment by cshesse** [comment]
That day is today
